//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcercampoVI.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleE
    {
        public int IdDetalle { get; set; }
        public int IdFactura { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public int CantidadPedido { get; set; }
        public decimal Precio { get; set; }
    
        public virtual FacturaE Factura { get; set; }
        public virtual ProductoE Producto { get; set; }
    }
}
