//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcercampoVI.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioXRolE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioXRolE()
        {
            this.Ruta = new HashSet<RutaE>();
            this.Vehiculo = new HashSet<VehiculoE>();
        }
    
        public int IdUsuarioXRol { get; set; }
        public int IdRol { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual RolE Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutaE> Ruta { get; set; }
        public virtual UsuariosE Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiculoE> Vehiculo { get; set; }
    }
}
