//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcercampoVI.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculoE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehiculoE()
        {
            this.Ruta = new HashSet<RutaE>();
        }
    
        public int IdVehiculo { get; set; }
        public int IdUsuarioXRol { get; set; }
        public int IdTIpoTransporte { get; set; }
        public string Placa { get; set; }
        public System.DateTime FechaSoat { get; set; }
        public int FechaTecicomecanica { get; set; }
        public string CapacidadVehiculo { get; set; }
    
        public virtual TipoTransporteE TipoTransporte { get; set; }
        public virtual UsuarioXRolE UsuarioXRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutaE> Ruta { get; set; }
    }
}
